name: Wecker
on: push
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Format
        run: |
          shopt -s globstar
          diff -u <(cat **/*.{cpp,hpp,ino}) <(clang-format -style=Google **/*.{cpp,hpp,ino})
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Lint
      run: |
        python -m pip install --upgrade pip
        pip install cpplint
        python -m cpplint --extensions=cpp,hpp,ino --filter=-legal/copyright wecker.* src/**/*pp
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile source
      uses: ArminJo/arduino-test-compile@v2
      with:
        debug-compile: true
        required-libraries: SevSeg
  graph:
    name: Graph
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile graph
        run: |
          sudo apt install graphviz
          dot info/design.dot -Tpng -o graph.png
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: graph-artifact
          path: graph.png
